# Generated by Django 4.2.5 on 2023-10-08 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
