# Generated by Django 4.2.5 on 2023-10-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('setA', 'setA'), ('setB', 'setB')], default='setA', max_length=10),
        ),
    ]
