# Generated by Django 4.2.3 on 2023-10-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('quantity', 'quantity'), ('days', 'days')], default='setA', max_length=10),
        ),
    ]
