# Generated by Django 4.2.3 on 2023-09-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_name', models.CharField(max_length=255)),
                ('p_category', models.CharField(max_length=255)),
                ('p_image_data', models.BinaryField()),
                ('p_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('p_discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
