# Generated by Django 4.2.5 on 2023-11-30 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main_product',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=255)),
                ('p_type', models.CharField(max_length=255)),
                ('otc_status', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3)),
                ('p_image', models.ImageField(default='static\\cat-icons\\syringe.png', upload_to='media/')),
                ('p_generics', models.CharField(max_length=255)),
                ('p_company', models.CharField(max_length=255)),
                ('medPerStrip', models.DecimalField(decimal_places=2, max_digits=10)),
                ('p_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('p_discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('p_Indications', models.TextField()),
                ('p_Pharmacology', models.TextField()),
                ('p_Dosage', models.TextField()),
                ('p_Interaction', models.TextField()),
                ('p_Contradictions', models.TextField()),
                ('p_Side_Effects', models.TextField()),
                ('p_Pregnancy', models.TextField()),
                ('p_Precautions', models.TextField()),
                ('p_Therapeutic', models.TextField()),
                ('p_Storage', models.CharField(max_length=255)),
                ('p_category', models.CharField(choices=[('BABY CARE', 'BABY CARE'), ('MENS', 'MENS'), ('Cold & Allergies', 'Cold & Allergies'), ('Heart Problems', 'Heart Problems'), ('Diabetes', 'Diabetes'), ('Respiratory Problems', 'Respiratory Problems'), ('Neurological Problems', 'Neurological Problems'), ('Arthritis or other types of pain', 'Arthritis or other types of pain'), ('Sexual Wellness', 'Sexual Wellness'), ('Herbal & Ayurvedic', 'Herbal & Ayurvedic'), ('Infant & Mothers care', 'Infant & Mothers care'), ('Supplements & Nutrition', 'Supplements & Nutrition')], max_length=255)),
                ('feature', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(max_length=15)),
                ('ordered_products', models.TextField(default='null')),
                ('prescriptions', models.JSONField(blank=True, default='null')),
                ('total', models.TextField(default='null')),
                ('del_adress', models.TextField(default='null')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('pending', 'pending')], default='pending', max_length=20)),
                ('Delivery_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Shipping', 'Shipping'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('paymentMobile', models.CharField(blank=True, max_length=15, null=True)),
                ('TxID', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='presciption_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(max_length=15)),
                ('prescription_img', models.TextField(default='null')),
                ('days', models.TextField(default='null')),
                ('del_adress', models.TextField(default='null')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('Delivery_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Shipping', 'Shipping'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile_MedList',
            fields=[
                ('phone_number', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('med_list', models.JSONField(default=dict)),
                ('prescriptions', models.JSONField(default=list)),
            ],
        ),
    ]
