# Generated by Django 3.0.14 on 2023-09-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main_product',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=255)),
                ('p_type', models.CharField(max_length=255)),
                ('p_image', models.ImageField(default='static\\cat-icons\\syringe.png', upload_to='media/')),
                ('p_generics', models.CharField(max_length=255)),
                ('p_company', models.CharField(max_length=255)),
                ('p_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('p_discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('p_Indications', models.TextField()),
                ('p_Pharmacology', models.TextField()),
                ('p_Dosage', models.TextField()),
                ('p_Interaction', models.TextField()),
                ('p_Contradictions', models.TextField()),
                ('p_Side_Effects', models.TextField()),
                ('p_Pregnancy', models.TextField()),
                ('p_Precautions', models.TextField()),
                ('p_Therapeutic', models.TextField()),
                ('p_Storage', models.CharField(max_length=255)),
                ('p_category', models.CharField(choices=[('BABY CARE', 'BABY CARE'), ('MENS', 'MENS')], max_length=255)),
                ('feature', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=255)),
            ],
        ),
    ]
