# Generated by Django 4.2.3 on 2023-10-17 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_product',
            old_name='piecePerStrip',
            new_name='medPerStrip',
        ),
    ]
