# Generated by Django 4.2.5 on 2023-10-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_MedList',
            fields=[
                ('phone_number', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('med_list', models.JSONField(default=dict)),
                ('prescriptions', models.JSONField(default=list)),
            ],
        ),
    ]
