# Generated by Django 4.2.3 on 2023-09-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_product',
            name='p_category',
            field=models.CharField(choices=[('BABY CARE', 'BABY CARE'), ('MENS', 'MENS'), ('Cold & Allergies', 'Cold & Allergies'), ('Heart Problems', 'Heart Problems'), ('Diabetes', 'Diabetes'), ('Respiratory Problems', 'Respiratory Problems'), ('Neurological Problems', 'Neurological Problems'), ('Arthritis or other types of pain', 'Arthritis or other types of pain'), ('Sexual Wellness', 'Sexual Wellness'), ('Herbal & Ayurvedic', 'Herbal & Ayurvedic'), ('Infant & Mothers care', 'Infant & Mothers care'), ('Supplements & Nutrition', 'Supplements & Nutrition')], max_length=255),
        ),
    ]
