# Generated by Django 4.2.3 on 2023-09-09 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_main_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='main_product',
            table=None,
        ),
    ]
