# Generated by Django 4.2.3 on 2023-10-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_orders_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirm', 'confirm')], default='pending', max_length=20),
        ),
    ]
