# Generated by Django 4.2.3 on 2023-09-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_main_product_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_product',
            name='p_category',
            field=models.CharField(choices=[('BABY CARE', 'BABY CARE'), ('MENS', 'MENS')], max_length=255),
        ), migrations.AlterField(
            model_name='main_product',
            name='feature',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=25),
        ),
    ]
