# Generated by Django 4.2.5 on 2023-10-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('confirm', 'confirm')], default='pending', max_length=20),
        ),
    ]
