# Generated by Django 4.2.3 on 2023-09-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_main_product_p_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_product',
            name='feature',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=255),
        ),
    ]
