# Generated by Django 4.2.3 on 2023-09-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_main_product_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_product',
            name='p_image',
            field=models.ImageField(default='static\\cat-icons\\syringe.png', upload_to='media/'),
        ),
    ]
