# Generated by Django 4.2.3 on 2023-11-13 19:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_main_product_otc_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='presciption_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(max_length=15)),
                ('prescription_img', models.TextField(default='null')),
                ('days', models.TextField(default='null')),
                ('del_adress', models.TextField(default='null')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], default='.....', max_length=20)),
            ],
        ),
    ]
