# Generated by Django 4.2.3 on 2023-11-13 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_presciption_order_orders_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presciption_order',
            name='orders_status',
        ),
    ]
