# Generated by Django 4.2.3 on 2023-11-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_presciption_order_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='prescriptions',
            field=models.JSONField(default=list),
        ),
    ]
