# Generated by Django 4.2.3 on 2023-11-13 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_orders_prescriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='prescriptions',
            new_name='prescription',
        ),
    ]
