# Generated by Django 4.2.3 on 2023-11-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_prescriptions_orders_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='prescription',
            field=models.JSONField(default='null'),
        ),
    ]
